_version = 4

[client]
	showDhOptionsButtonInMinecraftUi = true

		[client.advanced.graphics]
			enableSsao = true
			overrideVanillaGraphicsSettings = true

			[client.advanced.graphics.quality]
				lodChunkRenderDistanceRadius = 256
				horizontalQuality = "MEDIUM"
				maxHorizontalResolution = "BLOCK"
				verticalQuality = "MEDIUM"
				useCameraPositionForQualityDropOff = true
				transparency = "COMPLETE"
				lodShading = "AUTO"
				grassSideRendering = "FADE_TO_DIRT"
				ditherDhFade = true
				vanillaFadeMode = "DOUBLE_PASS"
				dhFadeFarClipPlane = true
				lodBiomeBlending = 3
				brightnessMultiplier = "1.0"
				saturationMultiplier = "1.0"

			[client.advanced.graphics.genericRendering]
				enableGenericRendering = true
				enableBeaconRendering = true
				beaconRenderHeight = 6000
				expandDistantBeacons = true
				enableCloudRendering = true
				enableMultiLayerClouds = true
				dimensionEnabledCloudRenderingCsv = "minecraft:overworld"

			[client.advanced.graphics.fog]
				enableDhFog = true
				colorMode = "USE_WORLD_FOG_COLOR"
				enableVanillaFog = false
				farFogStart = "0.4"
				farFogEnd = "1.0"
				farFogMin = "0.0"
				farFogMax = "1.0"
				farFogFalloff = "EXPONENTIAL_SQUARED"
				farFogDensity = "2.5"

				[client.advanced.graphics.fog.heightFog]
					heightFogMixMode = "SPHERICAL"
					heightFogDirection = "BELOW_SET_HEIGHT"
					heightFogBaseHeight = "80.0"
					heightFogStart = "0.0"
					heightFogEnd = "0.6"
					heightFogMin = "0.0"
					heightFogMax = "1.0"
					heightFogFalloff = "EXPONENTIAL_SQUARED"
					heightFogDensity = "20.0"

			[client.advanced.graphics.noiseTexture]
				enableNoiseTexture = true
				noiseSteps = 4
				noiseIntensity = "0.05"
				noiseDropoff = 1024

			[client.advanced.graphics.culling]
				overdrawPrevention = "-1.0"
				reduceOverdrawWithFastMovement = true
				enableCaveCulling = true
				caveCullingHeight = 60
				disableBeaconDistanceCulling = true
				disableFrustumCulling = false
				disableShadowPassFrustumCulling = false
				ignoredRenderBlockCsv = "minecraft:barrier,minecraft:structure_void,minecraft:light,minecraft:tripwire,minecraft:brown_mushroom"
				ignoredRenderCaveBlockCsv = ""
				waterSubSurfaceBlockReplacementCsv = "minecraft:kelp,minecraft:tall_seagrass,minecraft:seagrass"
				waterSurfaceBlockReplacementCsv = "minecraft:lily_pad"
				blocksToIgnore = "NON_COLLIDING"
				tintWithAvoidedBlocks = true

			[client.advanced.graphics.experimental]
				earthCurveRatio = 0
				ignoredDimensionCsv = "minecraft:overworld,minecraft:the_nether,minecraft:the_end"
				renderingEngine = "AUTO"

		[client.advanced.multiplayer]
			serverFolderNameMode = "NAME_ONLY"

		[client.advanced.autoUpdater]
			enableAutoUpdater = true
			enableSilentUpdates = false
			updateBranch = "AUTO"

		[client.advanced.debugging]
			rendererMode = "DEFAULT"
			debugRenderingColors = "OFF"
			enableWhiteWorld = false
			lodOnlyMode = false
			renderWireframe = false
			showOverlappingQuadErrors = false
			enableDebugKeybindings = false
			logBufferGarbageCollection = false

			[client.advanced.debugging.debugWireframe]
				enableRendering = false
				showWorldGenQueue = false
				showNetworkSyncOnLoadQueue = false
				showRenderSectionStatus = false
				showQuadTreeRenderStatus = false
				showFullDataUpdateStatus = false

			[client.advanced.debugging.openGl]
				overrideVanillaGLLogger = true
				onlyLogGlErrorsOnce = true
				glErrorHandlingMode = "IGNORE"

			[client.advanced.debugging.positionFinderDebugging]
				positionFinderEnable = false
				positionFinderDetailLevel = 6
				positionFinderXPos = 0
				positionFinderZPos = 0
				positionFinderMinBlockY = -64
				positionFinderMaxBlockY = 125
				positionFinderMarginPercent = "0.0"

			[client.advanced.debugging.f3Screen]
				showPlayerPos = true
				playerPosSectionDetailLevel = 6
				showThreadPools = true
				showRenderThreadTasks = false
				showCombinedObjectPools = false
				showSeparatedObjectPools = false
				showQueuedChunkUpdateCount = true
				showLevelStatus = true
				onlyShowRenderingLevels = true

			[client.advanced.debugging.exampleConfigScreen]
				boolTest = false
				byteTest = "8"
				intTest = 69420
				doubleTest = "420.69"
				shortTest = "69"
				longTest = "42069"
				floatTest = "0.42069"
				stringTest = "Test input box"
				listTest = ["option 1", "option 2", "option 3"]
				mapTest = "{}"
				linkableTest = 420

	[common.worldGenerator]
		enableDistantGeneration = true
		distantGeneratorMode = "FEATURES"
		showGenerationProgress = "DISABLED"
		generationProgressDisplayIntervalInSeconds = 2
		generationProgressDisableMessageDisplayTimeInSeconds = 20
		generationProgressIncludeChunksPerSecond = true
		generationCenterChunkX = 0
		generationCenterChunkZ = 0
		generationMaxChunkRadius = 0

	[common.lodBuilding]
		disableUnchangedChunkCheck = false
		dataCompression = "Z_STD_BLOCK"
		worldCompression = "VISUALLY_EQUAL"

		[common.lodBuilding.experimental]
			upsampleLowerDetailLodsToFillHoles = false

	[common.multiThreading]
		numberOfThreads = 8
		threadRunTimeRatio = "1.0"
		threadPriority = 5

	[common.logging]
		globalFileMaxLevel = "INFO"
		globalChatMaxLevel = "ERROR"
		logWorldGenEventToFile = "INFO"
		logWorldGenChunkLoadEventToFile = "INFO"
		logRendererEventToFile = "INFO"
		logRendererGLEventToFile = "INFO"
		logRendererGLEventToChat = "ERROR"
		logNetworkEventToFile = "INFO"
		logConnectionConfigChangesToFile = "WARN"

		[common.logging.warning]
			showLowMemoryWarningOnStartup = true
			showPoolInsufficientMemoryWarning = true
			showHighVanillaRenderDistanceWarning = true
			showReplayWarningOnStartup = true
			showUpdateQueueOverloadedChatWarning = false
			showSlowWorldGenSettingWarnings = true
			showModCompatibilityWarningsOnStartup = true
			logGarbageCollectorWarning = true
			showGarbageCollectorWarning = true

[server]
	sendLevelKeys = true
	serverId = -1228576138
	serverKey = ""
	levelKeyPrefix = ""
	enableServerGeneration = true
	generationRequestRateLimit = 20
	maxGenerationRequestDistance = 4096
	enableRealTimeUpdates = true
	realTimeUpdateDistanceRadiusInChunks = 256
	synchronizeOnLoad = true
	syncOnLoadRateLimit = 50
	maxSyncOnLoadRequestDistance = 4096
	playerBandwidthLimit = 500
	globalBandwidthLimit = 0
	enableAdaptiveTransferSpeed = false

	[server.experimental]
		enableNSizedGeneration = false
